---
# vars file for zabbix
zabbix_server_mysql_version: "{{ zabbix_version_major }}.2"

zabbix_agent_service: zabbix-agent

zabbix_server_service: zabbix-server

zabbix_proxy_service: zabbix-proxy

zabbix_java_gateway_service: zabbix-java-gateway

zabbix_httpd_service: httpd

_zabbix_repository:
  default: "https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb"
  Debian-8: "https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb"
  Debian-9: "https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb"
  Debian-10: "https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb"
  Ubuntu-14: "https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb"
  Ubuntu-16: "https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb"
  Ubuntu-18: "https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb"

zabbix_repository: "{{ _zabbix_repository[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_zabbix_repository[ansible_distribution] | default(_zabbix_repository['default'])) }}"

_zabbix_web_server_package:
  Debian: zabbix-frontend-php
  RedHat: zabbix-web-{{ zabbix_web_type | default('mysql') }}

zabbix_web_server_package: "{{ _zabbix_web_server_package[ansible_os_family] }}"

_zabbix_documentation_directory:
  Debian: "/usr/share/doc/zabbix-server-{{ zabbix_server_type }}"
  RedHat: "/usr/share/doc/zabbix-server-{{ zabbix_server_type }}-{{ zabbix_server_mysql_version }}"

zabbix_documentation_directory: "{{ _zabbix_documentation_directory[ansible_os_family] }}"

zabbix_unarchive_command: gunzip {{ zabbix_documentation_directory }}/create.sql.gz
zabbix_unarchive_creates: "{{ zabbix_documentation_directory }}/create.sql"

zabbix_mysql_target: "{{ zabbix_documentation_directory }}/create.sql"

# Get the list of required software from the mysql role.
zabbix_server_requirements: "{{ mysql_packages }}"